### ISSUE TITLE
Linked stylesheets?

### ISSUE THREAD

**Issue by jasonmcneill** [apearce/react-shadow-root#2]
Does react-shadow-root allow linking to separate CSS files? Or is it required to embed the styles within the component?

**Comment by apearce** [comment]
Yes it does. The link tag will be added to the shadow DOM and it will load and scope the styles appropriately. 

I am also currently working on adding support for Constructable Stylesheets.

Full disclosure: I hadn't tested linked sheets until just now since I figured people could just bundle the CSS with the component, but it does work.
